### ISSUE TITLE
Bug: Navigation Script Does NOT trigger sometimes

### ISSUE THREAD

**Issue by agentdeath253** [FalixNodes-Software/FalixNodes-Desktop#32]
Edited by @KorbsStudio 
**Describe the bug**
If the navigation script is not triggered by the software, the default tab will not be selected. Resulting in the software trying to show all tabs at once. 

**Expected behavior**
Tabs show as normal

**Screenshots**
![image](https://user-images.githubusercontent.com/51213244/164788867-936595fe-51bd-496d-b153-53b0a2d0724b.png)
Desktop:**
This can occur on all platforms.

___

Original by @agentdeath253
~~**Describe the bug**~~
~~panel falixnodes app glitched~~

~~**To Reproduce**~~
~~Steps to reproduce the behavior:~~
~~1. Go settings~~
~~2. Click on spanish~~
~~3. Scroll down to wait for it to load~~
~~4. See error~~

~~**Expected behavior**~~
~~Changed languge from english to spanish then panel glitched~~

~~**Screenshots**~~
~~https://derpy-father.xyz/TLnlgaiz~~

~~Desktop:**~~
~~Windows 11~~

**Comment by agentdeath253** [comment]
@KorbsStudio

**Comment by KorbsStudio** [comment]
![image](https://user-images.githubusercontent.com/51213244/164785201-74f0db2b-964e-4f7c-b51f-e8f5af88b32f.png)
This is what I get when using Spanish, only the controls need to be re-position for certain languages.

**Comment by agentdeath253** [comment]
okay the settings page is borken

**Comment by KorbsStudio** [comment]
That's just a script not loading properly, meaning I have to keep extending it's time to load.

**Comment by agentdeath253** [comment]
nice

**Comment by KorbsStudio** [comment]
I know it's been ages, but a patch update will fix this soon.
