### ISSUE TITLE
Bug: Fake positive adblock alert

### ISSUE THREAD

**Issue by seokjin93** [FalixNodes-Software/FalixNodes-Desktop#36]
**Describe the bug**

The desktop app shows me a adblock alert but i dont have it

**To Reproduce**
1. Open the app
2. Open the client panel or the game panel
3. Wait

**Expected behavior**
Click the i disabled my adblocker button and use it normally

**Screenshots**

![imagen](https://user-images.githubusercontent.com/81392269/180065010-0d535132-069d-4ca6-981e-b712f26b426c.png)

**Desktop:**
 - OS: [Windows 10 21H2]
 - Version [3.7.24]

**Comment by KorbsStudio** [comment]
There are a couple possibilities as to why this is happening on your end. 
1. You may be blocking ads system wide using your host file, you can check it by editing `C:\Windows\System32\drivers\etc\hosts`. To edit this, open your Powershell as admin and use:
```
notepad.exe C:\Windows\System32\drivers\etc\hosts
```

If the host file has a lot of URLs to Google or stuff like for advertisement, please remove them.

2. Ads didn't load in time. If ads don't load after a certain amount of time, FalixNodes will automatically assume there is an adblocker enabled, sometimes it's a false detection. 

___
### What is a host file?
File that manages the connection between a domain name server and an IP address in Linux and other operating systems. IP and domain names can be mapped in this simple text file.

**Comment by KorbsStudio** [comment]
Also I noticed "Update failed" error on the sidebar, meaning you're probably using a Microsoft Store version of FalixNodes Desktop. This annoying error has been removed an update, make sure FalixNodes Desktop is up to date in Microsoft Store. 

### How to Update Application on the Microsoft Store
1. Select Start **>** Microsoft Store.

2. After you've opened the Microsoft Store app, select Library **>** Get updates.

3. If there are updates, select Update all or choose which apps you want to update.

**Comment by seokjin93** [comment]
> Also I noticed "Update failed" error on the sidebar, meaning you're probably using a Microsoft Store version of FalixNodes Desktop. This annoying error has been removed an update, make sure FalixNodes Desktop is up to date in Microsoft Store. 
> 
> ### How to Update Application on the Microsoft Store
> 1. Select Start **>** Microsoft Store.
> 
> 2. After you've opened the Microsoft Store app, select Library **>** Get updates.
> 
> 3. If there are updates, select Update all or choose which apps you want to update.
> 
> 

No, im using the .exe app download es from the Official site
