### ISSUE TITLE
Sorry Korbs

### ISSUE THREAD

**Issue by AgentDeath253** [FalixNodes-Software/FalixNodes-Desktop#37]
Im sorry to do this to you korbs but i kinda have to
im having discord account issues at the moment but uh 814170568005124137 (Agent Death is banned and when i added the 834475302028836874 (darkness) double counter flagged it as a alt

again i am doing this because i know someone will bother to check here.
or email grace@falixnodes.net
![Screenshot (4)](https://user-images.githubusercontent.com/82530339/188293641-322afeef-8fb7-4d0c-a4c4-f221a04110cf.png)
^^ is the issue but my phone number is linked to a different account

again sorry korbs

**Comment by KorbsStudio** [comment]
;-;

**Comment by AgentDeath253** [comment]
yes i really did this

**Comment by AgentDeath253** [comment]
so any chance you could help?

**Comment by KorbsStudio** [comment]
I'm not sure if I can.

**Comment by AgentDeath253** [comment]
cant you like ping mocab

**Comment by AgentDeath253** [comment]
well i got to go
