### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by AgentDeath253** [FalixNodes-Software/FalixNodes-Desktop#39]
**Describe the bug**
Blog Page Images Dont Load

**To Reproduce**
1. open the app
2. open blog pages
3. see error

**Expected behavior**
images load

**Actual behavior**
images didn't load

**Screenshots**
![image](ImageURLGoesHere)

**Desktop:**
 - OS: [Windows 10]
 - Version [Latest]
![Screenshot (30)](https://user-images.githubusercontent.com/82530339/191384181-404d9d45-c1fe-49ca-9c8a-f92d3309c754.png)

**Comment by KorbsStudio** [comment]
The scripts for this is all fine, however because it's pulling this from "falixnodes.net", Cloudflare has prevented from hotlinking images making them fail to load. Also Cloudflare seems to be modifying the `onclick` which is breaking the scripts.

Sorry, I can't do much about this.

**Comment by KorbsStudio** [comment]
Blog tab will be replaced with something else then.

**Comment by AgentDeath253** [comment]
do you want this closed?
