### ISSUE TITLE
Bug:  Help Center Navbar

### ISSUE THREAD

**Issue by AgentDeath253** [FalixNodes-Software/FalixNodes-Desktop#40]
**Describe the bug**
Help Center Navbar Flashing in and out

**To Reproduce**
1. open desktop app
2. help center
3. See error

**Expected behavior**
Navbar Doesn't Glitch

**Actual behavior**
Navbar Glitches

**Screenshots**
https://cdn.discordapp.com/attachments/1020411940629119079/1021931589258719322/2022-09-20_16-50-13.mkv

**Desktop:**
 - OS: [Windows 10]
 - Version [latest]

**Comment by AgentDeath253** [comment]
sorry for .mvk

**Comment by AgentDeath253** [comment]
also help center question mark is always reloading

**Comment by KorbsStudio** [comment]
> also help center question mark is always reloading

Could be caused by ads, which I'm not allowed to touch for obvious reasons.
But I'll investigate the loading indicator anyway in case it's no ads causing this.

**Comment by AgentDeath253** [comment]
yeah i understand that

**Comment by AgentDeath253** [comment]
do you want me to close?

**Comment by KorbsStudio** [comment]
No, this is occurring in the latest version on my end. So this is an issue.

**Comment by AgentDeath253** [comment]
ok

**Comment by AgentDeath253** [comment]
the navbar glitching doesnt happen in 4.61.29 nor does the help center icon reloading

**Comment by AgentDeath253** [comment]
but the navbar doesnt show at all

**Comment by KorbsStudio** [comment]
CSS does need adjusting

**Comment by AgentDeath253** [comment]
you can still navigate

**Comment by KorbsStudio** [comment]
Okay, so it's using very very very old CSS code that gets injected in the help center tab. :grimacing: Very old code indeed.
I will update it.

**Comment by KorbsStudio** [comment]
That fact that I see `#lunrsearchresults` is not good, hasn't been used in over a year.

**Comment by AgentDeath253** [comment]
yikes
