### ISSUE TITLE
Bug: Game Panel Load Button

### ISSUE THREAD

**Issue by AgentDeath253** [FalixNodes-Software/FalixNodes-Desktop#43]
**Describe the bug**
Showing load game panel even if already loaded

**To Reproduce**
1.  enable load panel by default
2. exit out of desktop app
3. open desktop app
4. open game panel
5. see error
**Expected behavior**
just load without error

**Actual behavior**
load game panel button in backround

**Screenshots**
![image](https://user-images.githubusercontent.com/82530339/191567341-9100d7e4-257e-41fb-970a-94f28153b5fe.png)

**Desktop:**
 - OS: [Windows 10]
 - Version [Latest]

**Comment by KorbsStudio** [comment]
Hey Grace, thanks for submitting issues to FalixNodes Desktop. They'll be worked on today, starting now...

**Comment by KorbsStudio** [comment]
This issue does not occur on my end.
As expected behavior, the load button section does hide itself when loading the panel, even when enabling "Load Game Panel by Default" in the Settings page.

https://user-images.githubusercontent.com/51213244/191588201-71d1af68-c3f7-4c29-9872-02cd43ab22de.mp4

**Comment by KorbsStudio** [comment]
Also I see PhpMyAdmin on your end, which is not in the latest version. Please update: https://falixnodes.xyz/updates/stable/FalixNodes-Desktop.exe

**Comment by AgentDeath253** [comment]
Then Ms store is behind

**Comment by KorbsStudio** [comment]
Thanks for letting me, I'll have it updated tonight around 10pm EST.

**Comment by AgentDeath253** [comment]
I downloaded from the Microsoft store because download speed was slow from korbsstudio

**Comment by AgentDeath253** [comment]
Also could https://discord.com/channels/710503370187735160/829662493533667339/1022220734099111966 be fixed (it's killing me)

**Comment by KorbsStudio** [comment]
> I downloaded from the Microsoft store because download speed was slow from korbsstudio

Speeds have been improved since last week.

**Comment by AgentDeath253** [comment]
are you sure i got 10-100kb/s

**Comment by KorbsStudio** [comment]
The update speed of Korbs Studio Server should be 940Mbps, although the gateway has been acting up and may be causing issues today.

**Comment by AgentDeath253** [comment]
thats prob the issue

**Comment by AgentDeath253** [comment]
this doesnt show up in version 4.61.29

**Comment by AgentDeath253** [comment]
Solved Update To version 4.61.29

**Comment by AgentDeath253** [comment]
issue has resurfaced

**Comment by AgentDeath253** [comment]
version 4.61.29 
![image](https://user-images.githubusercontent.com/82530339/191634532-aa84bc54-f233-4f8b-8fb7-102b85e7e5a0.png)
![image](https://user-images.githubusercontent.com/82530339/191634552-d5d0eef8-a03d-4bc5-af58-5cd8d84cd1aa.png)

**Comment by KorbsStudio** [comment]
![tenor](https://user-images.githubusercontent.com/51213244/191634732-9ca12e2f-817f-45b1-9121-d0ebdd42eeb1.gif)

**Comment by AgentDeath253** [comment]
also same one i talked about in falix has came back
Js Error has occurred in the main process (when trying to close the app)
