### ISSUE TITLE
Bug: Google Login Give Malformed Data

### ISSUE THREAD

**Issue by AgentDeath253** [FalixNodes-Software/FalixNodes-Desktop#44]
**Describe the bug**

**To Reproduce**
1. Go client panel
2. press login with google
3. enter email then press enter
4. enter password
5. see error

**Expected behavior**
login with google without error

**Actual behavior**
gets malformed data error

**Screenshots**
Forgot the Screenshot

**Desktop:**
 - OS: [Windows 10]
 - Version [4.61.29]

**Comment by KorbsStudio** [comment]
Hi there, I just attempted to use the Google login on the client panel tab and it worked fine.
Which means I just created a new account. 

![image](https://user-images.githubusercontent.com/51213244/191604012-3f982db5-295c-4942-98db-9a11662df20d.png)

**Comment by AgentDeath253** [comment]
alts arent allowed 
![image](https://user-images.githubusercontent.com/82530339/191604821-426a58d7-c5aa-46ac-b070-1ad5cb214f4c.png)

**Comment by KorbsStudio** [comment]
I already deleted the account, but Google login works for me.

**Comment by AgentDeath253** [comment]
sus

**Comment by AgentDeath253** [comment]
Invalid/ Cant Be Copied
