### ISSUE TITLE
Bug: Microsoft Store Version shows ElectronJS Icon instead of FalixNodes

### ISSUE THREAD

**Issue by KorbsStudio** [FalixNodes-Software/FalixNodes-Desktop#45]
I'm aware :)

**Comment by AgentDeath253** [comment]
i should i reported this

**Comment by KorbsStudio** [comment]
:)

**Comment by AgentDeath253** [comment]
i meant i should have reported this

**Comment by KorbsStudio** [comment]
During editing process of the MSIX file, which is used for the Microsoft Store, the icons weren't replaced with the correct icons for FalixNodes Desktop.

My configuration is wrong in the `/build/` folder. The icons I have set for the Microsoft Store are suppose to be in the `/build/appx/` folder, not the root of the `/build/` folder.

I fix this soon.

![image](https://user-images.githubusercontent.com/51213244/191905407-3ab875eb-65d3-4604-a28d-68abff8ffdde.png)
